---
# NOTE: This is placeholder file to enable workflow action ansible-community/ansible-test-gh-action
# and it is not intended for actual publishing.
namespace: tool
name: sap_cluster_checks
version: 1.0.0
readme: README.md
authors:
  - Markus Moster <markus.moster@redhat.com>
description: Tool for SAP cluster checks.
license:
  - Apache-2.0
license_file: ''
tags:
  - sap
  - tool
dependencies: {}
repository: https://github.com/mmoster/tool.sap_cluster_checks
documentation: https://github.com/mmoster/tool.sap_cluster_checks/blob/main/README.md
homepage: https://github.com/mmoster/tool.sap_cluster_checks
issues: https://github.com/mmoster/tool.sap_cluster_checks/issues
build_ignore:
  - 'tests'
  - '.git*'
  - '.pylintrc*'
