extracted_at: '2026-07-28T15:08:03.410506'
source: running_cluster:ndc3hana03
cluster:
  name: R9_Sout
  pacemaker_version: 2.1.7
  rhel_version: RHEL 9
sap_hana:
  topology:
    resource_name: rsc_SAPHanaTopology_RH1_10
    clone_name: rsc_SAPHanaTopology_RH1_10-clone
    type: SAPHanaTopology
    attributes:
      InstanceNumber: '10'
      SID: RH1
  instance_number: '10'
  sid: RH1
  filesystem:
    resource_name: rsc_SAPHanaFilesystem_RH1_10
    clone_name: rsc_SAPHanaFilesystem_RH1_10-clone
    type: SAPHanaFilesystem
    attributes:
      InstanceNumber: '10'
      ON_FAIL_ACTION: fence
      SID: RH1
  controller:
    resource_name: rsc_SAPHanaController_RH1_10
    clone_name: rsc_SAPHanaController_RH1_10-clone
    type: SAPHanaController
    attributes:
      AUTOMATED_REGISTER: 'true'
      DUPLICATE_PRIMARY_TIMEOUT: '7200'
      InstanceNumber: '10'
      PREFER_SITE_TAKEOVER: 'true'
      SID: RH1
      priority: '100'
  resource_type: SAPHanaController
  resource_name: rsc_SAPHanaController_RH1_10
  automated_register: true
  duplicate_primary_timeout: 7200
  prefer_site_takeover: true
resources:
  vips:
  - resource_name: rsc_ip_MASTER1
    ip: 192.168.10.120
    cidr_netmask: ''
    nic: ''
  - resource_name: rsc_ip_SLAVE1
    ip: 192.168.10.130
    cidr_netmask: ''
    nic: ''
stonith:
  device: R9_fence_out
  type: fence_rhevm
  ip: lu0529.wdf.sap.corp
  pcmk_host_map: ndc1hana01:ndc1hana01-amemon;ndc1hana02:ndc1hana02-amemon;ndc1hana03:ndc1hana03-amemon;ndc2hana01:ndc2hana01-amemon;ndc2hana02:ndc2hana02-amemon;ndc2hana03:ndc2hana03-amemon;ndc3hana01:ndc3hana01-amemon;ndc3hana02:ndc3hana02-amemon;ndc3hana03:ndc3hana03-amemon
  host_map:
    ndc1hana01: ndc1hana01-amemon
    ndc1hana02: ndc1hana02-amemon
    ndc1hana03: ndc1hana03-amemon
    ndc2hana01: ndc2hana01-amemon
    ndc2hana02: ndc2hana02-amemon
    ndc2hana03: ndc2hana03-amemon
    ndc3hana01: ndc3hana01-amemon
    ndc3hana02: ndc3hana02-amemon
    ndc3hana03: ndc3hana03-amemon
  power_wait: '3'
  ssl: '1'
  ssl_insecure: '1'
  username: amemon@internal
  enabled: true
constraints:
  location:
  - 'resource ''rsc_ip_SLAVE1'' avoids node ''ndc3hana01'' with score INFINITY (id:
    location-rsc_ip_SLAVE1-ndc3hana01--INFINITY)'
  - 'resource ''rsc_ip_SLAVE1'' avoids node ''ndc3hana02'' with score INFINITY (id:
    location-rsc_ip_SLAVE1-ndc3hana02--INFINITY)'
  - 'resource ''rsc_ip_SLAVE1'' avoids node ''ndc3hana03'' with score INFINITY (id:
    location-rsc_ip_SLAVE1-ndc3hana03--INFINITY)'
  - 'resource ''rsc_ip_SLAVE1'' (id: location-rsc_ip_SLAVE1)'
  - 'Rules:'
  - 'Rule: boolean-op=and score=INFINITY (id: location-rsc_ip_SLAVE1-rule)'
  - 'Expression: master-rsc_SAPHana_RH1_HDB10 lt 105 (id: location-rsc_ip_SLAVE1-rule-expr)'
  - 'Expression: master-rsc_SAPHana_RH1_HDB10 gt 85 (id: location-rsc_ip_SLAVE1-rule-expr-1)'
  - 'resource pattern ''rsc_SAPHana*'' avoids node ''ndc2hana03'' with score INFINITY
    (id: no-hana-on-ndc2hana03)'
  - 'resource pattern ''rsc_SAPHana*'' avoids node ''ndc1hana03'' with score INFINITY
    (id: no-hana-on-ndc1hana03)'
  - 'resource ''rsc_SAPHanaTopology_RH1_10-clone'' avoids node ''ndc1hana03'' with
    score INFINITY (id: topology-avoids-majoritymaker)'
  - resource-discovery=never
  - 'resource ''rsc_SAPHanaFilesystem_RH1_10-clone'' avoids node ''ndc1hana03'' with
    score INFINITY (id: filesystem-avoids-majoritymaker)'
  - resource-discovery=never
  - 'resource ''rsc_SAPHanaController_RH1_10-clone'' avoids node ''ndc1hana03'' with
    score INFINITY (id: hana-avoids-majoritymaker)'
  - resource-discovery=never
  - 'resource ''rsc_SAPHanaController_RH1_10-clone'' (id: location-rsc_SAPHanaController_RH1_10-clone)'
  - 'Rules:'
  - 'Rule: boolean-op=or score=-INFINITY (id: location-rsc_SAPHanaController_RH1_10-clone-rule)'
  - 'Expression: pingd lt 1 (id: location-rsc_SAPHanaController_RH1_10-clone-rule-expr)'
  - 'Expression: not_defined pingd (id: location-rsc_SAPHanaController_RH1_10-clone-rule-expr-1)'
  - 'resource ''cln_SITEDC1'' (id: location-cln_SITEDC1)'
  - 'Rules:'
  - 'Rule: score=INFINITY (id: location-cln_SITEDC1-rule)'
  - 'Expression: site eq DC1 (id: location-cln_SITEDC1-rule-expr)'
  - 'resource ''cln_SITEDC2'' (id: location-cln_SITEDC2)'
  - 'Rules:'
  - 'Rule: score=INFINITY (id: location-cln_SITEDC2-rule)'
  - 'Expression: site eq DC2 (id: location-cln_SITEDC2-rule-expr)'
  - 'resource ''rsc_SAPHanaTopology_RH1_10-clone'' (id: location-rsc_SAPHanaTopology_RH1_10-clone)'
  - 'Rules:'
  - 'Rule: boolean-op=or score=-INFINITY (id: location-rsc_SAPHanaTopology_RH1_10-clone-rule)'
  - 'Expression: pingd lt 1 (id: location-rsc_SAPHanaTopology_RH1_10-clone-rule-expr)'
  - 'Expression: not_defined pingd (id: location-rsc_SAPHanaTopology_RH1_10-clone-rule-expr-1)'
  - 'resource ''cln_fence_DC1_unpromoted'' (id: location-cln_fence_DC1_unpromoted)'
  - 'Rules:'
  - 'Rule: boolean-op=and score=INFINITY (id: location-cln_fence_DC1_unpromoted-rule)'
  - 'Expression: site eq DC1 (id: location-cln_fence_DC1_unpromoted-rule-expr)'
  - 'Expression: pingd eq 1 (id: location-cln_fence_DC1_unpromoted-rule-expr-1)'
  - 'resource ''cln_fence_DC1_unpromoted'' (id: location-cln_fence_DC1_unpromoted-1)'
  - 'Rules:'
  - 'Rule: boolean-op=or score=-INFINITY (id: location-cln_fence_DC1_unpromoted-1-rule)'
  - 'Expression: pingd ne 1 (id: location-cln_fence_DC1_unpromoted-1-rule-expr)'
  - 'Expression: not_defined pingd (id: location-cln_fence_DC1_unpromoted-1-rule-expr-1)'
  - 'resource ''cln_fence_DC1_unpromoted'' (id: location-cln_fence_DC1_unpromoted-2)'
  - 'Rules:'
  - 'Rule: score=-INFINITY (id: location-cln_fence_DC1_unpromoted-2-rule)'
  - 'Expression: master-rsc_SAPHanaController_RH1_10 gt 140 (id: location-cln_fence_DC1_unpromoted-2-rule-expr)'
  - 'resource ''cln_fence_DC2_unpromoted'' (id: location-cln_fence_DC2_unpromoted)'
  - 'Rules:'
  - 'Rule: boolean-op=and score=INFINITY (id: location-cln_fence_DC2_unpromoted-rule)'
  - 'Expression: site eq DC2 (id: location-cln_fence_DC2_unpromoted-rule-expr)'
  - 'Expression: pingd eq 1 (id: location-cln_fence_DC2_unpromoted-rule-expr-1)'
  - 'resource ''cln_fence_DC2_unpromoted'' (id: location-cln_fence_DC2_unpromoted-1)'
  - 'Rules:'
  - 'Rule: boolean-op=or score=-INFINITY (id: location-cln_fence_DC2_unpromoted-1-rule)'
  - 'Expression: pingd ne 1 (id: location-cln_fence_DC2_unpromoted-1-rule-expr)'
  - 'Expression: not_defined pingd (id: location-cln_fence_DC2_unpromoted-1-rule-expr-1)'
  - 'resource ''cln_fence_DC2_unpromoted'' (id: location-cln_fence_DC2_unpromoted-2)'
  - 'Rules:'
  - 'Rule: score=-INFINITY (id: location-cln_fence_DC2_unpromoted-2-rule)'
  - 'Expression: master-rsc_SAPHanaController_RH1_10 gt 140 (id: location-cln_fence_DC2_unpromoted-2-rule-expr)'
  - 'resource ''cln_fence_DC2_unpromoted'' avoids node ''ndc1hana03'' with score INFINITY
    (id: location-cln_fence_DC2_unpromoted-ndc1hana03--INFINITY)'
  - 'resource ''cln_fence_DC1_unpromoted'' avoids node ''ndc1hana03'' with score INFINITY
    (id: location-cln_fence_DC1_unpromoted-ndc1hana03--INFINITY)'
  colocation:
  - 'Started resource ''rsc_ip_MASTER1'' with Promoted resource ''rsc_SAPHanaController_RH1_10-clone''
    (id: colocation-rsc_ip_MASTER1-rsc_SAPHanaController_RH1_10-clone-2000)'
  - score=2000
  - 'Order Constraints:'
  - 'start resource ''rsc_ip_MASTER1'' then start resource ''rsc_ip_SLAVE1'' (id:
    order-rsc_ip_MASTER1-rsc_ip_SLAVE1-mandatory)'
  - 'start resource ''rsc_SAPHanaTopology_RH1_10-clone'' then start resource ''rsc_SAPHanaController_RH1_10-clone''
    (id: order-rsc_SAPHanaTopology_RH1_10-clone-rsc_SAPHanaController_RH1_10-clone-mandatory)'
  - symmetrical=0
  - 'Alerts:'
  - 'Alert: alert-hana-1'
  - 'Path: /usr/bin/SAPHanaSR-alert-fencing'
  - 'Receives:'
  - nodes
  - fencing
  - 'Attributes: alert-hana-1-instance_attributes'
  - alert_uptime_threshold=300
  - 'Resources Defaults:'
  - 'Meta Attrs: build-resource-defaults'
  - 'migration-threshold=1000 (id: build-resource-defaults-migration-threshold)'
  - 'Cluster Properties: cib-bootstrap-options'
  - cluster-infrastructure=corosync
  - cluster-name=R9_Sout
  - dc-version=2.1.7-5.3.el9_4-0f7f88312
  - hana_fence_action=reboot
  - hana_fence_timeout=250
  - have-watchdog=false
  - last-lrm-refresh=1779357203
  - maintenance-mode=false
  - stonith-enabled=true
  order: []
  hana_excluded_node: ndc1hana03
  majority_maker: null
properties:
  cluster-infrastructure: corosync
  cluster-name: R9_Sout
  dc-version: 2.1.7-5.3.el9_4-0f7f88312
  hana_fence_action: reboot
  hana_fence_timeout: '250'
  have-watchdog: 'false'
  last-lrm-refresh: '1779357203'
  maintenance-mode: 'false'
  stonith-enabled: 'true'
